name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env:
        OU_CONTAINER_DEST: ${{ secrets.OU_CONTAINER_DEST }}
      run: docker build . --file Dockerfile --tag $OU_CONTAINER_DEST
    - name: login
      env:
        DOCKER_REGISTRY_URL: docker.io
        DOCKER_USERNAME: ${{ secrets.OU_REG_USER }}
        DOCKER_PASSWORD: ${{ secrets.OU_REG_PASSWORD }}
      uses: actions/docker/login@master
    - name: push
      env:
        OU_CONTAINER_DEST: ${{ secrets.OU_CONTAINER_DEST }}
      run: docker push  ${{ secrets.OU_CONTAINER_DEST }}
